/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import symboltable.Type;

public abstract class PExpr extends Node {
  private Type type = Type.UNDEFINED;

  public Type getType() {
    return type;
  }

  public void setType(Type type) {
    this.type = type;
  }
}
